# Generated by Django 2.2.9 on 2020-01-10 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympics', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Olympic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1896), django.core.validators.MaxValueValidator(32767)])),
                ('season', models.CharField(choices=[('S', 'Summer'), ('W', 'Winter')], max_length=1)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
