# Generated by Django 2.2.9 on 2020-01-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympics', '0003_olympic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noc', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
