# Generated by Django 3.0.2 on 2020-01-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympics', '0007_auto_20200113_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='notes',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
