# Generated by Django 3.0.2 on 2020-01-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympics', '0008_team_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='age',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='height',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='weight',
        ),
        migrations.AddField(
            model_name='olympicevent',
            name='age',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='olympicevent',
            name='height',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='olympicevent',
            name='weight',
            field=models.PositiveSmallIntegerField(default=None),
        ),
    ]
