# Generated by Django 2.2.9 on 2020-01-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympics', '0009_auto_20200114_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='notes',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
