# Generated by Django 2.2.9 on 2020-01-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympics', '0011_auto_20200114_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympicevent',
            name='age',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='olympicevent',
            name='height',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='olympicevent',
            name='weight',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
    ]
